kind: pipeline
name: default

steps:
- name: test
  image: rikorose/gcc-cmake
  commands:
  - apt-get install curl zip unzip tar
  - mkdir -p build
  - cd build; cmake ..
  - cmake --build -C build
  - ctest -C build