kind: pipeline
name: default

steps:
- name: test
  image: rikorose/gcc-cmake
  commands:
  - apt-get update; apt-get -y install curl zip unzip tar
  - mkdir -p build
  - cd build; cmake ..
  - cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  - cd build; ctest